#pragma once

#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLEVOFANCONTROL_DIALOG         102
#define IDR_MAINFRAME                   128

#define IDC_STATIC                      (-1)
#define IDC_LIST_STATUS                 1001
#define IDC_CHECK_TAKEOVER              1024
#define IDC_CHECK_FORCE                 1025
#define IDC_CHECK_LINEAR                1026
#define IDC_EDIT_TREANSITION            1027
#define IDC_EDIT_INTERVAL               1028
#define IDC_BUTTON_RESET                1029
#define IDC_BUTTON_SAVE                 1030
#define IDC_BUTTON_LOAD                 1031
#define IDC_EDIT_FORCE_TEMP             1032
#define IDC_CHECK_AUTORUN               1033
#define IDC_CHECK_SOFTCONTROL           1040

#define IDC_STATIC_STATUS_GROUP         1100
#define IDC_STATIC_CPU_CURVE            1101
#define IDC_STATIC_GPU_CURVE            1102
#define IDC_STATIC_CPU_TITLE            1103
#define IDC_STATIC_GPU_TITLE            1104
#define IDC_STATIC_NODE_GROUP           1105
#define IDC_STATIC_SETTINGS_GROUP       1106
#define IDC_STATIC_NODE_INDEX_LABEL     1108
#define IDC_STATIC_NODE_TEMP_LABEL      1109
#define IDC_STATIC_NODE_DUTY_LABEL      1110
#define IDC_STATIC_INTERVAL_LABEL       1111
#define IDC_STATIC_TRANSITION_LABEL     1112
#define IDC_STATIC_FORCE_LABEL          1113
#define IDC_COMBO_CURVE                 1117
#define IDC_EDIT_NODE_INDEX             1118
#define IDC_EDIT_NODE_TEMP              1119
#define IDC_EDIT_NODE_DUTY              1120
#define IDC_BUTTON_CURVE_ADD            1121
#define IDC_BUTTON_CURVE_DELETE         1122
#define IDC_BUTTON_CURVE_RESET          1123
#define IDC_CURVE_CPU                   1124
#define IDC_CURVE_GPU                   1125
#define IDC_STATIC_CURVE_LABEL          1126
#define IDC_STATIC_CLOSE_BEHAVIOR_LABEL 1127
#define IDC_COMBO_CLOSE_BEHAVIOR        1128
#define IDC_STATIC_FONT_SIZE_LABEL      1129
#define IDC_EDIT_FONT_SIZE              1130
#define IDC_SPIN_FONT_SIZE              1131
#define IDD_PRESET_MANAGER_DIALOG       103
#define IDC_STATIC_PRESETS_GROUP        1132
#define IDC_CHECK_AUTO_SWITCH           1133
#define IDC_STATIC_ACTIVE_PRESET        1134
#define IDC_BUTTON_MANAGE_PRESETS       1135
#define IDC_LIST_PRESETS                1136
#define IDC_STATIC_PRESET_NAME_LABEL    1137
#define IDC_EDIT_PRESET_NAME            1138
#define IDC_STATIC_PRESET_PATTERN_LABEL 1139
#define IDC_EDIT_PRESET_PATTERN         1140
#define IDC_BUTTON_PRESET_NEW           1141
#define IDC_BUTTON_PRESET_SAVE_RULE     1142
#define IDC_BUTTON_PRESET_DELETE        1143
#define IDC_BUTTON_PRESET_UP            1144
#define IDC_BUTTON_PRESET_DOWN          1145
#define IDC_BUTTON_PRESET_USE           1146
